#!/bin/sh -f

# script to build examples in the inexlib_py source distribution.
# Here we enforce the usage of an external Python.

#set -x

bush_home=../../../../bush

. ${bush_home}/args

build_args="-sys_Python ${build_args}"

./exlib_build ${build_args}




