#!/bin/sh -f

bush_home=`dirname $0`/../../../../bush
. ${bush_home}/args
. ${bush_home}/exlib_header

pack_name=inexlib_py   
version=1.1.0

/bin/rm -R -f ${build_path}/distrib
/bin/mkdir -p ${build_path}/distrib/${pack_name}/${version}/bin
/bin/mkdir -p ${build_path}/distrib/${pack_name}/${version}/modules

to=${build_path}/distrib/${pack_name}/${version}

items="hello_py h1d_spy plotter_spy_screen mandel_py"
for item in ${items} ; do
  if [ ! -x ${build_path}/${item} ] ; then
    echo "${build_path}/${item} not found."
  else    
    /bin/cp ${build_path}/${item} ${to}/bin/.
  fi
done

if [ ! -x ../py/${build_dir}/inlib_swig_py.so ] ; then
  echo "../py/${build_dir}/inlib_swig_py.so not found."
else    
  /bin/cp ../py/${build_dir}/inlib_swig_py.so ${to}/modules/.
fi

if [ ! -x ../py/${build_dir}/exlib_offscreen_swig_py.so ] ; then
  echo "../py/${build_dir}/exlib_offscreen_swig_py.so not found."
else    
  /bin/cp ../py/${build_dir}/exlib_offscreen_swig_py.so ${to}/modules/.
fi

if [ ! -x ../py/${build_dir}/exlib_window_swig_py.so ] ; then
  echo "../py/${build_dir}/exlib_window_swig_py.so not found."
else    
  /bin/cp ../py/${build_dir}/exlib_window_swig_py.so ${to}/modules/.
fi

if [ ! -x ../py/${build_dir}/which_py ] ; then
  echo "../py/${build_dir}/which_py not found."
else    
  /bin/cp ../py/${build_dir}/which_py ${to}/bin/.
fi

/bin/cp ../py/run       ${to}/.
/bin/cp ../py/spark_run ${to}/.

/bin/cp -R ./res ${to}/.
/bin/cp -R ../../data ${to}/.

find ../py -maxdepth 1 -name '*.py' -exec /bin/cp {} ${to}/. \;

platform=`${bush_home}/platform "${cpp_compiler}"`
if [ "${platform}" = "" ] ; then
  echo "bush/app_distrib : can't guess platform for ${cpp_compiler}."
else
  if [ ${build_verbose} = yes ] ; then
    echo "bush/app_distrib : platform is ${platform}."
  fi
    
  #///////////////////////////////////////////////////
  #/// zip : /////////////////////////////////////////
  #///////////////////////////////////////////////////
  save_dir=`pwd`
        
  ${bush_home}/check_app zip 'zip not found, we use tar.'
  use_status=$?;
  if [ ${use_status} != 0 ] ; then
    cd ${build_path}/distrib
    tar cf ${pack_name}-${version}-${platform}.tar ./${pack_name}
    cd ${save_dir}
  else
    cd ${build_path}/distrib
    zip -qr ${pack_name}-${version}-${platform}.zip ./${pack_name}
    cd ${save_dir}
  fi
fi
