@section inexlib_py_download_app_store Apple AppStore

  inexlib_py is available on the AppStore since January 2012.

@section inexlib_py_download_android Android Market

  inexlib_py is available on the Android Market for devices
 with at least Android-2.0. Note that the inexlib_py-release.apk
 is also available from the download area.

@section inexlib_py_download_cocoa Cocoa (Mac desktop)

  On a Mac, download and unzip the inexlib_py.app.zip, then click
 on the inexlib_py icon (or do : open inexlib_py.app, from a terminal).
 Remember that data files are searched within the directory :
@verbatim
     ~/Documents/inexlib_py
@endverbatim
