@section pmx_download_app_store Apple AppStore

  pmx is available on the AppStore since January 2012.

@section pmx_download_android Android Market

  pmx is available on the Android Market for devices
 with at least Android-2.0. Note that the pmx-release.apk
 is also available from the download area.

@section pmx_download_cocoa Cocoa (Mac desktop)

  On a Mac, download and unzip the pmx.app.zip, then click
 on the pmx icon (or do : open pmx.app, from a terminal).
 Remember that data files are searched within the directory :
@verbatim
     ~/Documents/pmx
@endverbatim
