#!/bin/sh -f

# Copyright (C) 2010, Guy Barrand. All rights reserved.
# See the file exlib.license for terms.

bush_home=../../../../bush

. ${bush_home}/args

build_use_py3=no

items="${build_args}"
build_args=
for item in ${items} ; do  
  case ${item} in
    -py3) build_use_py3=yes;;
    -*) build_args="${build_args} ${item}";;
  esac
done

. ${bush_home}/header

#build_args="${save_args}"

if [ ${build_verbose} = yes ] ; then echo "exlib/examples/py/build : enforce use of sys Python."; fi
build_args="${build_args} -sys_Python"

spy_dir=spy
if [ ${build_use_py3} = yes ] ; then spy_dir=spy3; fi

/bin/mkdir -p ${build_path}

exlib_mgr=../../../exlib/mgr

save_dir=`pwd`

cd ${exlib_mgr}
if [ ${build_verbose} = yes ] ; then
  ./build_res -v
else
  ./build_res
fi      
cd ${save_dir}

cd ${exlib_mgr}
./build ${build_args} ../exlib/${spy_dir}/inlib_swig_py.cpp
cd ${save_dir}
if [ -f ${exlib_mgr}/${build_dir}/inlib_swig_py.${pgpy} ] ; then
  /bin/mv ${exlib_mgr}/${build_dir}/inlib_swig_py.${pgpy} ${build_path}/.
else
  echo "${exlib_mgr}/${build_dir}/inlib_swig_py.${pgpy} not found."
fi

cd ${exlib_mgr}
./build ${build_args} ../exlib/${spy_dir}/exlib_offscreen_swig_py.cpp
cd ${save_dir}
if [ -f ${exlib_mgr}/${build_dir}/exlib_offscreen_swig_py.${pgpy} ] ; then
  /bin/mv ${exlib_mgr}/${build_dir}/exlib_offscreen_swig_py.${pgpy} ${build_path}/.
else
  echo "${exlib_mgr}/${build_dir}/exlib_offscreen_swig_py.${pgpy} not found."
fi

cd ${exlib_mgr}
./build ${build_args} ../exlib/${spy_dir}/exlib_window_swig_py.cpp
cd ${save_dir}
if [ -f ${exlib_mgr}/${build_dir}/exlib_window_swig_py.${pgpy} ] ; then
  /bin/mv ${exlib_mgr}/${build_dir}/exlib_window_swig_py.${pgpy} ${build_path}/.
else
  echo "${exlib_mgr}/${build_dir}/exlib_window_swig_py.${pgpy} not found."
fi

/bin/rm -f ${build_path}/which_py
if [ ${build_use_py3} = yes ] ; then
cat <<EOF3 > ${build_path}/which_py 
#!/bin/sh -f
echo Python3
EOF3
else
cat <<EOF > ${build_path}/which_py 
#!/bin/sh -f
echo Python
EOF
fi
chmod a+x ${build_path}/which_py
