#!/bin/sh -f

bush_home=../../../../bush

. ${bush_home}/args

build_use_py3=no

items="${build_args}"
build_args=
for item in ${items} ; do  
  case ${item} in
    -py3) build_use_py3=yes;;
    -*) build_args="${build_args} ${item}";;
  esac
done

. ${bush_home}/header

#build_args="${save_args}"

if [ ${build_verbose} = yes ] ; then echo "exlib/examples/py/build : enforce use of sys Python."; fi
build_args="${build_args} -sys_Python"

group=spy
if [ ${build_use_py3} = yes ] ; then group=spy3; fi

/bin/mkdir -p ${build_path}

exlib_mgr=../../../exlib/mgr

save_dir=`pwd`

cd ${exlib_mgr}
./build ${build_args} ../exlib/${group}/inlib_swig_py.cpp
cd ${save_dir}
if [ -f ${exlib_mgr}/${build_dir}/inlib_swig_py.${pgpy} ] ; then
  /bin/mv ${exlib_mgr}/${build_dir}/inlib_swig_py.${pgpy} ${build_path}/.
else
  echo "${exlib_mgr}/${build_dir}/inlib_swig_py.${pgpy} not found."
fi

cd ${exlib_mgr}
./build ${build_args} ../exlib/${group}/exlib_offscreen_swig_py.cpp
cd ${save_dir}
if [ -f ${exlib_mgr}/${build_dir}/exlib_offscreen_swig_py.${pgpy} ] ; then
  /bin/mv ${exlib_mgr}/${build_dir}/exlib_offscreen_swig_py.${pgpy} ${build_path}/.
else
  echo "${exlib_mgr}/${build_dir}/exlib_offscreen_swig_py.${pgpy} not found."
fi

cd ${exlib_mgr}
./build ${build_args} ../exlib/${group}/exlib_window_swig_py.cpp
cd ${save_dir}
if [ -f ${exlib_mgr}/${build_dir}/exlib_window_swig_py.${pgpy} ] ; then
  /bin/mv ${exlib_mgr}/${build_dir}/exlib_window_swig_py.${pgpy} ${build_path}/.
else
  echo "${exlib_mgr}/${build_dir}/exlib_window_swig_py.${pgpy} not found."
fi
